---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secrets
  namespace: default
spec:
  encryptedData:
    DJANGO_SECRET_KEY: AgBuk2kETXS9ILDquCppD63vV6YAerdpKLCtwU7e6NldpG3mBV8LCJgX6DaxHA89wfZTZNUQ7EX1A/IJvb5o40dWfx5t8TudApD25bWhninxNWvuGBjk9Lk8MZJ4ZzH1YB3S1N6KB1SQnIeQcdXpEHVGtGW+aveedAaPPj7UMqe0kt7VCUq3u4VPhTZCdq+H4vRnJ1yP0LK4Va4SRx0RIN7Y+ZIND2QBHqlTYvLDh6tNqRbAvsipIrJYxGmHv+4WdUm1Js1ekZBJnVkNDNkAS+LzGT/0g1rEAtH+g/RQRldemxc7KL2Cpd1WSEcO4JsBlHahxTfYSYKXSxvD3OWmVcJcIBrGIBvR/4+y3ae35ZihneWz1Rj65G7vUMG51zDb+P0F8ydC+JQmD8TTp+buEVFeX9eM3wSXZX9LdLR23T6AxA7u69f11yTqUEbLA+WHH8L64wyNCMVD01NQo/Khivu9lKmfUkpZlIGovlmnUMJY3GUL8pFbHhRq4LJMBnYGkfRk336Ms85uXdSilgAayo3Cpye1wf0S9XI1cGVHeajaAmZ74oZhcyOr7cousi4Ay/NnnrwQ5qDgB8P3waJ0dOXPHFLbCsHJxVaUa9lam5r0+nD5hm/uSCGarxbPfRpxnPeU2ccm7j3b/DhQjR+3YQM44hu8L8X3cTjGIkrzMZLClGHWeDFV/Lccq5YHRgM4b4TaKa5EkMOfieEl6ke3osjMbZl9yVGEq+agXeZXsIDOFcj/k1Op85zPhosBOExAsjg=
  template:
    metadata:
      name: app-secrets
      namespace: default
